# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            PROTOLOUS
tagline:          'agilidade, tecnologia e sociedade'
description:      ''
url:              http://protolous.org
baseurl:          /
permalink:        blog/:year/:i_month/:i_day/:title

author:
  name:           'Lourenço P. Soares'
  url:            https://twitter.com/protolous

paginate:         3

gems:
  - jekyll-redirect-from